package net.mcreator.yvanchuyaoshou;

import java.io.File;
import net.minecraftforge.common.config.Configuration;

/* loaded from: 妖兽-mc1.12.2-2.0.16.jar:net/mcreator/yvanchuyaoshou/Config.class */
public class Config {
    public static Configuration config;
    public static int AllMobsNumMax;
    public static int AllXiuShiNumMax;
    public static int CheckR;
    public static int LvNiNumMin;
    public static int LvNiNumMax;
    public static int LvNiOdds;
    public static int JiHunXieNumMin;
    public static int JiHunXieNumMax;
    public static int JiHunXieOdds;
    public static int JiHunXie2NumMin;
    public static int JiHunXie2NumMax;
    public static int JiHunXie2Odds;
    public static int YuWaNumMin;
    public static int YuWaNumMax;
    public static int YuWaOdds;
    public static int YuWa2NumMin;
    public static int YuWa2NumMax;
    public static int YuWa2Odds;
    public static int HeiZhuNumMin;
    public static int HeiZhuNumMax;
    public static int HeiZhuOdds;
    public static int HeiZhu2NumMin;
    public static int HeiZhu2NumMax;
    public static int HeiZhu2Odds;
    public static int YingXiaoNumMin;
    public static int YingXiaoNumMax;
    public static int YingXiaoOdds;
    public static int YingXiao2NumMin;
    public static int YingXiao2NumMax;
    public static int YingXiao2Odds;
    public static int YingXiao3NumMin;
    public static int YingXiao3NumMax;
    public static int YingXiao3Odds;
    public static int YingXiao4NumMin;
    public static int YingXiao4NumMax;
    public static int YingXiao4Odds;
    public static int JunEYiNumMin;
    public static int JunEYiNumMax;
    public static int JunEYiOdds;
    public static int JunEYi2NumMin;
    public static int JunEYi2NumMax;
    public static int JunEYi2Odds;
    public static int JunEYi3NumMin;
    public static int JunEYi3NumMax;
    public static int JunEYi3Odds;
    public static int JunEYi4NumMin;
    public static int JunEYi4NumMax;
    public static int JunEYi4Odds;
    public static int GuLangNumMin;
    public static int GuLangNumMax;
    public static int GuLangOdds;
    public static int PuNiaoNumMin;
    public static int PuNiaoNumMax;
    public static int PuNiaoOdds;
    public static int LeiBanLuNumMin;
    public static int LeiBanLuNumMax;
    public static int LeiBanLuOdds;
    public static int LeiBanLu2NumMin;
    public static int LeiBanLu2NumMax;
    public static int LeiBanLu2Odds;
    public static int LeiBanLu3NumMin;
    public static int LeiBanLu3NumMax;
    public static int LeiBanLu3Odds;
    public static int ShiFengTuoNumMin;
    public static int ShiFengTuoNumMax;
    public static int ShiFengTuoOdds;
    public static int ShiFengTuo2NumMin;
    public static int ShiFengTuo2NumMax;
    public static int ShiFengTuo2Odds;
    public static int LinHaiShouHuangNumMin;
    public static int LinHaiShouHuangNumMax;
    public static int LinHaiShouHuangOdds;
    public static int LinHaiShouHuang2NumMin;
    public static int LinHaiShouHuang2NumMax;
    public static int LinHaiShouHuang2Odds;
    public static int LeiYuanJuENumMin;
    public static int LeiYuanJuENumMax;
    public static int LeiYuanJuEOdds;
    public static int LeiYuanJuE2NumMin;
    public static int LeiYuanJuE2NumMax;
    public static int LeiYuanJuE2Odds;
    public static int BaiZeNumMin;
    public static int BaiZeNumMax;
    public static int BaiZeOdds;
    public static int JiuWeiHuoHuNumMin;
    public static int JiuWeiHuoHuNumMax;
    public static int JiuWeiHuoHuOdds;
    public static int QiLinNumMin;
    public static int QiLinNumMax;
    public static boolean QiLinSum;
    public static int QiLinOdds;
    public static int SanXiuNumMin;
    public static int SanXiuNumMax;
    public static int SanXiuOdds;
    public static int SanXiu2NumMin;
    public static int SanXiu2NumMax;
    public static int SanXiu2Odds;
    public static int SanXiu3NumMin;
    public static int SanXiu3NumMax;
    public static int SanXiu3Odds;
    public static int SanXiu4NumMin;
    public static int SanXiu4NumMax;
    public static int SanXiu4Odds;
    public static int SanXiu5NumMin;
    public static int SanXiu5NumMax;
    public static int SanXiu5Odds;
    public static int MoXiuNumMin;
    public static int MoXiuNumMax;
    public static int MoXiuOdds;
    public static int MoXiu2NumMin;
    public static int MoXiu2NumMax;
    public static int MoXiu2Odds;
    public static int MoXiu3NumMin;
    public static int MoXiu3NumMax;
    public static int MoXiu3Odds;
    public static int MoXiu4NumMin;
    public static int MoXiu4NumMax;
    public static int MoXiu4Odds;
    public static int MoXiu5NumMin;
    public static int MoXiu5NumMax;
    public static int MoXiu5Odds;
    public static int HunTieShouNumMin;
    public static int HunTieShouNumMax;
    public static int HunTieShouOdds;
    public static int HunTieShou2NumMin;
    public static int HunTieShou2NumMax;
    public static int HunTieShou2Odds;
    public static int ShouGuanYinBingNumMin;
    public static int ShouGuanYinBingNumMax;
    public static int ShouGuanYinBingOdds;

    public static void init(File configFile) {
        if (config == null) {
            config = new Configuration(configFile);
            syncConfig();
        }
    }

    public static void syncConfig() {
        AllMobsNumMax = config.getInt("AllMobsNumMax", "general", 13, 0, 999, "全部修仙生物生成最大值(一个玩家一定范围内的)");
        AllXiuShiNumMax = config.getInt("AllXiuShiNumMax", "general", 5, 0, 999, "所有修士生成最大值(一个玩家一定范围内的，且包含在所有修仙生物最大值中)");
        CheckR = config.getInt("CheckR", "general", 64, 0, 999, "检测范围半径(修仙生物生成最大值的检测范围)");
        LvNiNumMin = config.getInt("LvNiNumMin", "general", 1, 0, 999, "一阶绿泥最小生成数(如果＞0，那么会在概率生成失败后固定生成最小数量)");
        LvNiNumMax = config.getInt("LvNiNumMax", "general", 2, 0, 999, "一阶绿泥最大生成数");
        LvNiOdds = config.getInt("LvNiOdds", "general", 50, 0, 100, "一阶绿泥生成概率，单位%");
        JiHunXieNumMin = config.getInt("JiHunXieNumMin", "general", 1, 0, 999, "一阶寄魂蟹最小生成数(如果＞0，那么会在概率生成失败后固定生成最小数量)");
        JiHunXieNumMax = config.getInt("JiHunXieNumMax", "general", 3, 0, 999, "一阶寄魂蟹最大生成数");
        JiHunXieOdds = config.getInt("JiHunXieOdds", "general", 50, 0, 100, "一阶寄魂蟹生成概率，单位%");
        JiHunXie2NumMin = config.getInt("JiHunXie2NumMin", "general", 1, 0, 999, "二阶寄魂蟹最小生成数(如果＞0，那么会在概率生成失败后固定生成最小数量)");
        JiHunXie2NumMax = config.getInt("JiHunXie2NumMax", "general", 1, 0, 999, "二阶寄魂蟹最大生成数");
        JiHunXie2Odds = config.getInt("JiHunXie2Odds", "general", 50, 0, 100, "二阶寄魂蟹生成概率，单位%");
        YuWaNumMin = config.getInt("YuWaNumMin", "general", 1, 0, 999, "一阶雨蛙最小生成数(如果＞0，那么会在概率生成失败后固定生成最小数量)");
        YuWaNumMax = config.getInt("YuWaNumMax", "general", 1, 0, 999, "一阶雨蛙最大生成数");
        YuWaOdds = config.getInt("YuWaOdds", "general", 50, 0, 100, "一阶雨蛙生成概率，单位%");
        YuWa2NumMin = config.getInt("YuWa2NumMin", "general", 1, 0, 999, "二阶雨蛙最小生成数(如果＞0，那么会在概率生成失败后固定生成最小数量)");
        YuWa2NumMax = config.getInt("YuWa2NumMax", "general", 1, 0, 999, "二阶雨蛙最大生成数");
        YuWa2Odds = config.getInt("YuWa2Odds", "general", 50, 0, 100, "二阶雨蛙生成概率，单位%");
        HeiZhuNumMin = config.getInt("HeiZhuNumMin", "general", 1, 0, 999, "二阶黑蛛最小生成数(如果＞0，那么会在概率生成失败后固定生成最小数量)");
        HeiZhuNumMax = config.getInt("HeiZhuNumMax", "general", 1, 0, 999, "二阶黑蛛最大生成数");
        HeiZhuOdds = config.getInt("HeiZhuOdds", "general", 50, 0, 100, "二阶黑蛛生成概率，单位%");
        HeiZhu2NumMin = config.getInt("HeiZhu2NumMin", "general", 1, 0, 999, "五阶黑蛛最小生成数(如果＞0，那么会在概率生成失败后固定生成最小数量)");
        HeiZhu2NumMax = config.getInt("HeiZhu2NumMax", "general", 1, 0, 999, "五阶黑蛛最大生成数");
        HeiZhu2Odds = config.getInt("HeiZhu2Odds", "general", 50, 0, 100, "五阶黑蛛生成概率，单位%");
        YingXiaoNumMin = config.getInt("YingXiaoNumMin", "general", 1, 0, 999, "二阶鹰枭最小生成数(如果＞0，那么会在概率生成失败后固定生成最小数量)");
        YingXiaoNumMax = config.getInt("YingXiaoNumMax", "general", 2, 0, 999, "二阶鹰枭最大生成数");
        YingXiaoOdds = config.getInt("YingXiaoOdds", "general", 50, 0, 100, "二阶鹰枭生成概率，单位%");
        YingXiao2NumMin = config.getInt("YingXiao2NumMin", "general", 1, 0, 999, "三阶鹰枭最小生成数(如果＞0，那么会在概率生成失败后固定生成最小数量)");
        YingXiao2NumMax = config.getInt("YingXiao2NumMax", "general", 1, 0, 999, "三阶鹰枭最大生成数");
        YingXiao2Odds = config.getInt("YingXiao2Odds", "general", 50, 0, 100, "三阶鹰枭生成概率，单位%");
        YingXiao3NumMin = config.getInt("YingXiao3NumMin", "general", 1, 0, 999, "四阶鹰枭最小生成数(如果＞0，那么会在概率生成失败后固定生成最小数量)");
        YingXiao3NumMax = config.getInt("YingXiao3NumMax", "general", 1, 0, 999, "四阶鹰枭最大生成数");
        YingXiao3Odds = config.getInt("YingXiao3Odds", "general", 50, 0, 100, "四阶鹰枭生成概率，单位%");
        YingXiao4NumMin = config.getInt("YingXiao4NumMin", "general", 1, 0, 999, "五阶鹰枭最小生成数(如果＞0，那么会在概率生成失败后固定生成最小数量)");
        YingXiao4NumMax = config.getInt("YingXiao4NumMax", "general", 1, 0, 999, "五阶鹰枭最大生成数");
        YingXiao4Odds = config.getInt("YingXiao4Odds", "general", 50, 0, 100, "五阶鹰枭生成概率，单位%");
        JunEYiNumMin = config.getInt("JunEYiNumMin", "general", 1, 0, 999, "二阶军颚蚁最小生成数(如果＞0，那么会在概率生成失败后固定生成最小数量)");
        JunEYiNumMax = config.getInt("JunEYiNumMax", "general", 3, 0, 999, "二阶军颚蚁最大生成数");
        JunEYiOdds = config.getInt("JunEYiOdds", "general", 50, 0, 100, "二阶军颚蚁生成概率，单位%");
        JunEYi2NumMin = config.getInt("JunEYi2NumMin", "general", 1, 0, 999, "三阶军颚蚁最小生成数(如果＞0，那么会在概率生成失败后固定生成最小数量)");
        JunEYi2NumMax = config.getInt("JunEYi2NumMax", "general", 1, 0, 999, "三阶军颚蚁最大生成数");
        JunEYi2Odds = config.getInt("JunEYi2Odds", "general", 50, 0, 100, "三阶军颚蚁生成概率，单位%");
        JunEYi3NumMin = config.getInt("JunEYi3NumMin", "general", 1, 0, 999, "四阶军颚蚁最小生成数(如果＞0，那么会在概率生成失败后固定生成最小数量)");
        JunEYi3NumMax = config.getInt("JunEYi3NumMax", "general", 1, 0, 999, "四阶军颚蚁最大生成数");
        JunEYi3Odds = config.getInt("JunEYi3Odds", "general", 50, 0, 100, "四阶军颚蚁生成概率，单位%");
        JunEYi4NumMin = config.getInt("JunEYi4NumMin", "general", 1, 0, 999, "五阶军颚蚁最小生成数(如果＞0，那么会在概率生成失败后固定生成最小数量)");
        JunEYi4NumMax = config.getInt("JunEYi4NumMax", "general", 1, 0, 999, "五阶军颚蚁最大生成数");
        JunEYi4Odds = config.getInt("JunEYi4Odds", "general", 50, 0, 100, "五阶军颚蚁生成概率，单位%");
        GuLangNumMin = config.getInt("GuLangNumMin", "general", 1, 0, 999, "三阶骨狼最小生成数(如果＞0，那么会在概率生成失败后固定生成最小数量)");
        GuLangNumMax = config.getInt("GuLangNumMax", "general", 1, 0, 999, "三阶骨狼最大生成数");
        GuLangOdds = config.getInt("GuLangOdds", "general", 50, 0, 100, "三阶骨狼生成概率，单位%");
        PuNiaoNumMin = config.getInt("PuNiaoNumMin", "general", 1, 0, 999, "三阶蒲鸟最小生成数(如果＞0，那么会在概率生成失败后固定生成最小数量)");
        PuNiaoNumMax = config.getInt("PuNiaoNumMax", "general", 2, 0, 999, "三阶蒲鸟最大生成数");
        PuNiaoOdds = config.getInt("PuNiaoOdds", "general", 50, 0, 100, "三阶蒲鸟生成概率，单位%");
        LeiBanLuNumMin = config.getInt("LeiBanLuNumMin", "general", 1, 0, 999, "三阶雷斑鹿最小生成数(如果＞0，那么会在概率生成失败后固定生成最小数量)");
        LeiBanLuNumMax = config.getInt("LeiBanLuNumMax", "general", 3, 0, 999, "三阶雷斑鹿最大生成数");
        LeiBanLuOdds = config.getInt("LeiBanLuOdds", "general", 50, 0, 100, "三阶雷斑鹿生成概率，单位%");
        LeiBanLu2NumMin = config.getInt("LeiBanLu2NumMin", "general", 1, 0, 999, "四阶雷斑鹿最小生成数(如果＞0，那么会在概率生成失败后固定生成最小数量)");
        LeiBanLu2NumMax = config.getInt("LeiBanLu2NumMax", "general", 1, 0, 999, "四阶雷斑鹿最大生成数");
        LeiBanLu2Odds = config.getInt("LeiBanLu2Odds", "general", 50, 0, 100, "四阶雷斑鹿生成概率，单位%");
        LeiBanLu3NumMin = config.getInt("LeiBanLu3NumMin", "general", 1, 0, 999, "五阶雷斑鹿最小生成数(如果＞0，那么会在概率生成失败后固定生成最小数量)");
        LeiBanLu3NumMax = config.getInt("LeiBanLu3NumMax", "general", 1, 0, 999, "五阶雷斑鹿最大生成数");
        LeiBanLu3Odds = config.getInt("LeiBanLu3Odds", "general", 50, 0, 100, "五阶雷斑鹿生成概率，单位%");
        ShiFengTuoNumMin = config.getInt("ShiFengTuoNumMin", "general", 1, 0, 999, "四阶石峰驼最小生成数(如果＞0，那么会在概率生成失败后固定生成最小数量)");
        ShiFengTuoNumMax = config.getInt("ShiFengTuoNumMax", "general", 2, 0, 999, "四阶石峰驼最大生成数");
        ShiFengTuoOdds = config.getInt("ShiFengTuoOdds", "general", 50, 0, 100, "四阶石峰驼生成概率，单位%");
        ShiFengTuo2NumMin = config.getInt("ShiFengTuo2NumMin", "general", 1, 0, 999, "五阶石峰驼最小生成数(如果＞0，那么会在概率生成失败后固定生成最小数量)");
        ShiFengTuo2NumMax = config.getInt("ShiFengTuo2NumMax", "general", 1, 0, 999, "五阶石峰驼最大生成数");
        ShiFengTuo2Odds = config.getInt("ShiFengTuo2Odds", "general", 50, 0, 100, "五阶石峰驼生成概率，单位%");
        LinHaiShouHuangNumMin = config.getInt("LinHaiShouHuangNumMin", "general", 1, 0, 999, "四阶林海兽皇最小生成数(如果＞0，那么会在概率生成失败后固定生成最小数量)");
        LinHaiShouHuangNumMax = config.getInt("LinHaiShouHuangNumMax", "general", 2, 0, 999, "四阶林海兽皇最大生成数");
        LinHaiShouHuangOdds = config.getInt("LinHaiShouHuangOdds", "general", 50, 0, 100, "四阶林海兽皇生成概率，单位%");
        LinHaiShouHuang2NumMin = config.getInt("LinHaiShouHuang2NumMin", "general", 1, 0, 999, "五阶林海兽皇最小生成数(如果＞0，那么会在概率生成失败后固定生成最小数量)");
        LinHaiShouHuang2NumMax = config.getInt("LinHaiShouHuang2NumMax", "general", 1, 0, 999, "五阶林海兽皇最大生成数");
        LinHaiShouHuang2Odds = config.getInt("LinHaiShouHuang2Odds", "general", 50, 0, 100, "五阶林海兽皇生成概率，单位%");
        LeiYuanJuENumMin = config.getInt("LeiYuanJuENumMin", "general", 1, 0, 999, "四阶雷原巨鳄最小生成数(如果＞0，那么会在概率生成失败后固定生成最小数量)");
        LeiYuanJuENumMax = config.getInt("LeiYuanJuENumMax", "general", 3, 0, 999, "四阶雷原巨鳄最大生成数");
        LeiYuanJuEOdds = config.getInt("LeiYuanJuEOdds", "general", 50, 0, 100, "四阶雷原巨鳄生成概率，单位%");
        LeiYuanJuE2NumMin = config.getInt("LeiYuanJuE2NumMin", "general", 1, 0, 999, "五阶雷原巨鳄最小生成数(如果＞0，那么会在概率生成失败后固定生成最小数量)");
        LeiYuanJuE2NumMax = config.getInt("LeiYuanJuE2NumMax", "general", 1, 0, 999, "五阶雷原巨鳄最大生成数");
        LeiYuanJuE2Odds = config.getInt("LeiYuanJuE2Odds", "general", 50, 0, 100, "五阶雷原巨鳄生成概率，单位%");
        BaiZeNumMin = config.getInt("BaiZeNumMin", "general", 1, 0, 999, "五阶白泽最小生成数(如果＞0，那么会在概率生成失败后固定生成最小数量)");
        BaiZeNumMax = config.getInt("BaiZeNumMax", "general", 1, 0, 999, "五阶白泽最大生成数");
        BaiZeOdds = config.getInt("BaiZeOdds", "general", 50, 0, 100, "五阶白泽生成概率，单位%");
        JiuWeiHuoHuNumMin = config.getInt("JiuWeiHuoHuNumMin", "general", 1, 0, 999, "五阶九尾火狐最小生成数(如果＞0，那么会在概率生成失败后固定生成最小数量)");
        JiuWeiHuoHuNumMax = config.getInt("JiuWeiHuoHuNumMax", "general", 3, 0, 999, "五阶九尾火狐最大生成数");
        JiuWeiHuoHuOdds = config.getInt("JiuWeiHuoHuOdds", "general", 50, 0, 100, "五阶九尾火狐生成概率，单位%");
        QiLinNumMin = config.getInt("QiLinNumMin", "general", 1, 0, 999, "五阶麒麟最小生成数(如果＞0，那么会在概率生成失败后固定生成最小数量)");
        QiLinNumMax = config.getInt("QiLinNumMax", "general", 2, 0, 999, "五阶麒麟最大生成数");
        QiLinOdds = config.getInt("QiLinOdds", "general", 50, 0, 100, "五阶麒麟生成概率，单位%");
        SanXiuNumMin = config.getInt("SanXiuNumMin", "general", 1, 0, 999, "炼气散修最小生成数(如果＞0，那么会在概率生成失败后固定生成最小数量)");
        SanXiuNumMax = config.getInt("SanXiuNumMax", "general", 2, 0, 999, "炼气散修最大生成数");
        SanXiuOdds = config.getInt("SanXiuOdds", "general", 50, 0, 100, "炼气散修生成概率，单位%");
        SanXiu2NumMin = config.getInt("SanXiu2NumMin", "general", 1, 0, 999, "筑基散修最小生成数(如果＞0，那么会在概率生成失败后固定生成最小数量)");
        SanXiu2NumMax = config.getInt("SanXiu2NumMax", "general", 2, 0, 999, "筑基散修最大生成数");
        SanXiu2Odds = config.getInt("SanXiu2Odds", "general", 50, 0, 100, "筑基散修生成概率，单位%");
        SanXiu3NumMin = config.getInt("SanXiu3NumMin", "general", 1, 0, 999, "结丹散修最小生成数(如果＞0，那么会在概率生成失败后固定生成最小数量)");
        SanXiu3NumMax = config.getInt("SanXiu3NumMax", "general", 1, 0, 999, "结丹散修最大生成数");
        SanXiu3Odds = config.getInt("SanXiu3Odds", "general", 50, 0, 100, "结丹散修生成概率，单位%");
        SanXiu4NumMin = config.getInt("SanXiu4NumMin", "general", 1, 0, 999, "元婴散修最小生成数(如果＞0，那么会在概率生成失败后固定生成最小数量)");
        SanXiu4NumMax = config.getInt("SanXiu4NumMax", "general", 1, 0, 999, "元婴散修最大生成数");
        SanXiu4Odds = config.getInt("SanXiu4Odds", "general", 50, 0, 100, "元婴散修生成概率，单位%");
        SanXiu5NumMin = config.getInt("SanXiu5NumMin", "general", 1, 0, 999, "化神散修最小生成数(如果＞0，那么会在概率生成失败后固定生成最小数量)");
        SanXiu5NumMax = config.getInt("SanXiu5NumMax", "general", 1, 0, 999, "化神散修最大生成数");
        SanXiu5Odds = config.getInt("SanXiu5Odds", "general", 50, 0, 100, "化神散修生成概率，单位%");
        MoXiuNumMin = config.getInt("MoXiuNumMin", "general", 1, 0, 999, "炼气魔修最小生成数(如果＞0，那么会在概率生成失败后固定生成最小数量)");
        MoXiuNumMax = config.getInt("MoXiuNumMax", "general", 2, 0, 999, "炼气魔修最大生成数");
        MoXiuOdds = config.getInt("MoXiuOdds", "general", 50, 0, 100, "炼气魔修生成概率，单位%");
        MoXiu2NumMin = config.getInt("MoXiu2NumMin", "general", 1, 0, 999, "筑基魔修最小生成数(如果＞0，那么会在概率生成失败后固定生成最小数量)");
        MoXiu2NumMax = config.getInt("MoXiu2NumMax", "general", 2, 0, 999, "筑基魔修最大生成数");
        MoXiu2Odds = config.getInt("MoXiu2Odds", "general", 50, 0, 100, "筑基魔修生成概率，单位%");
        MoXiu3NumMin = config.getInt("MoXiu3NumMin", "general", 1, 0, 999, "结丹魔修最小生成数(如果＞0，那么会在概率生成失败后固定生成最小数量)");
        MoXiu3NumMax = config.getInt("MoXiu3NumMax", "general", 1, 0, 999, "结丹魔修最大生成数");
        MoXiu3Odds = config.getInt("MoXiu3Odds", "general", 50, 0, 100, "结丹魔修生成概率，单位%");
        MoXiu4NumMin = config.getInt("MoXiu4NumMin", "general", 1, 0, 999, "元婴魔修最小生成数(如果＞0，那么会在概率生成失败后固定生成最小数量)");
        MoXiu4NumMax = config.getInt("MoXiu4NumMax", "general", 1, 0, 999, "元婴魔修最大生成数");
        MoXiu4Odds = config.getInt("MoXiu4Odds", "general", 50, 0, 100, "元婴魔修生成概率，单位%");
        MoXiu5NumMin = config.getInt("MoXiu5NumMin", "general", 1, 0, 999, "化神魔修最小生成数(如果＞0，那么会在概率生成失败后固定生成最小数量)");
        MoXiu5NumMax = config.getInt("MoXiu5NumMax", "general", 1, 0, 999, "化神魔修最大生成数");
        MoXiu5Odds = config.getInt("MoXiu5Odds", "general", 50, 0, 100, "化神魔修生成概率，单位%");
        HunTieShouNumMin = config.getInt("HunTieShouNumMin", "general", 1, 0, 999, "一阶魂铁兽最小生成数(如果＞0，那么会在概率生成失败后固定生成最小数量)");
        HunTieShouNumMax = config.getInt("HunTieShouNumMax", "general", 2, 0, 999, "一阶魂铁兽最大生成数");
        HunTieShouOdds = config.getInt("HunTieShouOdds", "general", 50, 0, 100, "一阶魂铁兽生成概率，单位%");
        HunTieShou2NumMin = config.getInt("HunTieShou2NumMin", "general", 1, 0, 999, "二阶魂铁兽最小生成数(如果＞0，那么会在概率生成失败后固定生成最小数量)");
        HunTieShou2NumMax = config.getInt("HunTieShou2NumMax", "general", 1, 0, 999, "二阶魂铁兽最大生成数");
        HunTieShou2Odds = config.getInt("HunTieShou2Odds", "general", 50, 0, 100, "二阶魂铁兽生成概率，单位%");
        ShouGuanYinBingNumMin = config.getInt("ShouGuanYinBingNumMin", "general", 1, 0, 999, "二阶守棺阴兵最小生成数(如果＞0，那么会在概率生成失败后固定生成最小数量)");
        ShouGuanYinBingNumMax = config.getInt("ShouGuanYinBingNumMax", "general", 1, 0, 999, "二阶守棺阴兵最大生成数");
        ShouGuanYinBingOdds = config.getInt("ShouGuanYinBingOdds", "general", 50, 0, 100, "二阶守棺阴兵生成概率，单位%");
        if (config.hasChanged()) {
            config.save();
        }
    }
}
