modLoader="javafml"
loaderVersion="[31,)"

[[mods]]
modId="diguoshidai"
version="1.0.0"
displayName="diguoshidai"
credits="Created using mod maker MCreator - https://mcreator.net/about"
displayURL="https://mcreator.net"
authors="dell"

[[dependencies.diguoshidai]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2]"
    ordering="NONE"
    side="BOTH"




